### ISSUE TITLE
Improve sentry clustering

### ISSUE THREAD

**Issue by greboid** [DMDirc/Infrastructure#3]
Need to look and see how sentry clusters reports, and adjust it to a method similar to the old error reporter. 

I think it's checking the whole stack trace, whereas we used to just look at the first DMDirc frame.

Groups are determined based on the checksum, calculated in manager.py: 

https://github.com/getsentry/sentry/blob/15c0291074087408c6f66ac1619365b148b9084c/src/sentry/manager.py#L50 

The hash for exceptions are built here: 

https://github.com/getsentry/sentry/blob/cb3b54a58b301b7a89dc7f8c2de64b4a97af3f0a/src/sentry/interfaces.py#L777 

And finally the hash for stack traces here: 

https://github.com/getsentry/sentry/blob/cb3b54a58b301b7a89dc7f8c2de64b4a97af3f0a/src/sentry/interfaces.py#L591 

Which basically includes the hash of every frame.

**Comment by csmith** [comment]
New Sentry allows us to manually merge clusters, no need for this.
